#!/usr/bin/env bash
set -euo pipefail

# Script to prepare the repository for a safe git push.
# It inspects modified files, attempts local builds for affected projects,
# runs Norminette/autofix if available, and generates suggested commit commands.

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

echo "Repo root: $ROOT"

if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  echo "Not a git repository. Run this from inside the repo." >&2
  exit 1
fi

echo "Modified files (staged or not):"
git status --porcelain

MODIFIED=$(git diff --name-only --diff-filter=ACMRTUXB || true)
STAGED=$(git diff --cached --name-only || true)

if [ -z "$MODIFIED" ] && [ -z "$STAGED" ]; then
  echo "No modified or staged files detected. Nothing to prepare."
  exit 0
fi

echo "Changed (unstaged):"
printf "%s\n" "$MODIFIED"
echo "Staged:" 
printf "%s\n" "$STAGED"

# Consolidate a list of affected files (prefer staged when present)
ALL_FILES=$(printf "%s\n%s\n" "$STAGED" "$MODIFIED" | sed '/^$/d' | sort -u)

echo "Generating affected projects list..."
projects=$(printf "%s\n" "$ALL_FILES" | awk -F/ '($1=="42" && $2=="C"){print "42/C/"$3}' | sort -u)

if [ -z "$projects" ]; then
  echo "No 42/C projects affected. Skipping project builds."
else
  echo "Affected projects:" 
  printf "%s\n" "$projects"
fi

BUILD_FAILED=0
for p in $projects; do
  if [ -f "$p/Makefile" ]; then
    echo "\nBuilding $p"
    (cd "$p" && make) || { echo "Build failed for $p" >&2; BUILD_FAILED=1; }
  else
    echo "No Makefile in $p; skipping build."
  fi
done

if [ "$BUILD_FAILED" -ne 0 ]; then
  echo "One or more builds failed. Inspect build output before pushing." >&2
fi

echo "\nRunning Norminette/autofix where applicable..."
changed_c_files=$(printf "%s\n" "$ALL_FILES" | grep -E '\\.(c|h)$' || true)
if [ -n "$changed_c_files" ]; then
  if [ -x ".tools/normi-autofix.sh" ]; then
    echo "Using .tools/normi-autofix.sh on changed files"
    for f in $changed_c_files; do
      echo "Fixing Norminette issues in: $f"
      bash .tools/normi-autofix.sh "$f" || true
    done
  elif command -v norminette >/dev/null 2>&1; then
    echo "Running norminette on changed files (read-only)..."
    for f in $changed_c_files; do
      norminette "$f" || true
    done
  else
    echo "Norminette not available. Install or use .tools/normi-autofix.sh to auto-fix style issues."
  fi
else
  echo "No C source/header changes to check with Norminette."
fi

SUGGESTED="scripts/suggested_commits.txt"
echo "# Suggested commit plan" > "$SUGGESTED"
echo "# Generated by scripts/prepare_push.sh" >> "$SUGGESTED"
echo >> "$SUGGESTED"

for p in $projects; do
  echo "Project: $p" >> "$SUGGESTED"
  printf "%s\n" "$ALL_FILES" | grep "^$p/" | sed 's/^/  /' >> "$SUGGESTED" || true
  echo >> "$SUGGESTED"
  echo "Suggested commit message:" >> "$SUGGESTED"
  echo "  <suma breve de cambios en $p>" >> "$SUGGESTED"
  echo >> "$SUGGESTED"
  echo "Suggested commands:" >> "$SUGGESTED"
  echo "  git add <files listed above>" >> "$SUGGESTED"
  echo "  git commit -m \"$p: <mensaje claro y corto>\"" >> "$SUGGESTED"
  echo >> "$SUGGESTED"
done

echo "Suggested commit plan written to: $SUGGESTED"

echo "\nSummary of next manual steps (no automatic push):"
echo "- Inspect builds and tests outputs."
echo "- Review and run the suggested commits in $SUGGESTED."
echo "- Run any project-specific tests under tests/ for the affected projects."
echo "- When ready, run:"
echo "    git push origin $(git rev-parse --abbrev-ref HEAD)"

exit 0
